# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodavnica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('ime', models.CharField(max_length=25)),
                ('prezime', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('tip', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Narudzba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_narudzbe', models.DateTimeField(verbose_name='datum narudzbe')),
                ('adresa', models.CharField(max_length=200)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='Proizvodjac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocjena', models.IntegerField(default=0)),
                ('tekst', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='StatusNarudzbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StavkaNarudzbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='artikal',
            old_name='vrsta',
            new_name='kategorija',
        ),
        migrations.AddField(
            model_name='stavkanarudzbe',
            name='artikal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Artikal'),
        ),
        migrations.AddField(
            model_name='stavkanarudzbe',
            name='narudzba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Narudzba'),
        ),
        migrations.AddField(
            model_name='recenzija',
            name='artikal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Artikal'),
        ),
        migrations.AddField(
            model_name='recenzija',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Korisnik'),
        ),
        migrations.AddField(
            model_name='narudzba',
            name='status_narudzbe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.StatusNarudzbe'),
        ),
        migrations.AddField(
            model_name='artikal',
            name='proizvodjac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Proizvodjac'),
            preserve_default=False,
        ),
    ]
