# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prodavnica', '0003_auto_20170806_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StavkaKorpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolicina', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='artikal',
            name='kategorija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prodavnica.Kategorija'),
        ),
        migrations.AlterField(
            model_name='artikal',
            name='proizvodjac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prodavnica.Proizvodjac'),
        ),
        migrations.AlterField(
            model_name='narudzba',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recenzija',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stavkakorpe',
            name='artikal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Artikal'),
        ),
        migrations.AddField(
            model_name='stavkakorpe',
            name='korpa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prodavnica.Korpa'),
        ),
    ]
